import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    city: 'Vellore', login: 'Login', hero_h1_acc: 'Fast. Smart.', hero_h1_sub: 'Reliable Delivery.',
    hero_sub: 'Delivering across Vellore — quick, safe & on time.',
    hero_live: 'Now Live in Vellore District', lang_label: '🌐 Choose Language:',
    hero_title: 'Send Packages Anywhere in Minutes 🚀',
    hero_pickup: '📍 Pickup Location', hero_drop: '🎯 Drop Location', hero_btn: 'Get Estimate →',
    carousel_1_title: 'Fast Delivery in 30 mins', carousel_1_sub: 'Get your packages delivered lightning fast across the city.',
    carousel_2_title: 'Bulk Delivery for Shops', carousel_2_sub: 'Special rates and dedicated vehicles for shop owners.',
    carousel_3_title: 'Safe & Secure Courier', carousel_3_sub: 'Every package is insured and tracked in real-time.',
    ticker_1: '🔥 20% OFF First Delivery', ticker_2: '📦 Free Pickup Today',
    route1: 'Vellore → Chennai', route2: 'Vellore → Bangalore', route3: 'Vellore → Ranipet',
    route4: 'Vellore → Katpadi', route5: 'Vellore → Gudiyatham', min: 'min', hr: 'hr',
    home_q: 'What would you like to do?', home_q_sub: 'Choose an option to get started',
    card_book: 'Book Delivery', card_book_desc: 'Send a package anywhere in Vellore — fast & affordable.',
    card_track: 'Track Order', card_track_desc: 'Check your delivery status in real time.',
    card_partner: 'Partner Login', card_partner_desc: 'Accept orders and track your earnings.',
    card_support: 'Support', card_support_desc: 'Have an issue? We\'ll resolve it fast.',
    stat_orders: 'Orders Delivered', stat_partners: 'Active Partners', stat_cities: 'Cities Covered',
    feat_title: 'Why SmartDrop?', feat_sub: 'Built for Vellore\'s needs',
    f1t: 'Express Delivery', f1d: 'Under 10 km in 20–30 min.',
    f2t: 'Multi-Payment', f2d: 'UPI, Card, Net Banking or COD.',
    f3t: 'Live Tracking', f3d: 'Real-time updates pickup to doorstep.',
    f4t: 'OTP Security', f4d: 'Dual OTP at pickup & delivery.',
    f5t: 'Partner Jobs', f5d: '₹30/delivery + ₹5/km + bonuses.',
    f6t: 'Secure Admin', f6d: 'Hidden portal. Role-based access only.',
    footer_tag: 'Fast. Smart. Reliable Delivery.', footer_rights: 'All rights reserved.',
    book_title: '📦 Book a Delivery', book_sub: 'Smart pricing · Multi-payment · Instant partner assignment',
    pickup_label: '📍 Pickup Location', drop_label: '🎯 Drop Location',
    parcel_type: '📦 Parcel Type', type_normal: 'Normal', type_fragile: 'Fragile', type_food: 'Food', type_doc: 'Document',
    size_label: '📐 Parcel Size', size_small: 'Small (+₹10)', size_medium: 'Medium (+₹20)', size_large: 'Large (+₹40)',
    speed_label: '⚡ Speed', speed_normal: '🚶 Normal', speed_express: '⚡ Express',
    pay_label: '💳 Payment Method', customer_label: 'Your Name', phone_label: 'Phone Number',
    place_order: '🚀 Place Order', calculating: 'Calculating fare...',
    fare_summary: '💰 Fare Summary', base_fare: 'Base Fare', distance: 'Distance', type_charge: 'Type Charge',
    size_charge: 'Size Charge', express_charge: 'Express Charge', total_fare: 'Total Fare',
    delivery_type: '📦 Delivery Type', single: 'Single', multi: 'Multiple', bulk: 'Bulk',
    add_item: '➕ Add Item', remove: 'Remove', item_name: 'Item Name', quantity: 'Quantity',
    total_weight: 'Total Weight', weight_kg: 'kg', per_kg_rate: 'Per kg rate', item_charge: 'Item Charge', bulk_package: 'Bulk Package',
    track_title: '📍 Track Your Order', track_sub: 'Enter your order ID to see live status',
    track_placeholder: 'e.g. ORD-1001', track_btn: 'Track', not_found: 'Order not found. Check your ID.',
    support_title: '💬 Customer Support', support_sub: 'Submit your issue — we\'ll respond within 24 hours',
    your_name: 'Your Name', contact_label: 'Phone / Email', order_id_opt: 'Order ID (optional)',
    issue_type: 'Issue Type', delivery_issue: 'Delivery Issue', payment_issue: 'Payment Issue',
    partner_issue: 'Partner Issue', other_issue: 'Other', describe_issue: 'Describe Your Issue',
    submit_btn: '📤 Submit Request', ticket_submitted: 'Ticket Submitted!',
    ticket_id_label: 'Your ticket ID:', ticket_respond: 'We\'ll respond within 24 hours.',
    submit_another: 'Submit Another',
    history_title: '📋 Order History', history_sub: 'All your deliveries',
    all_orders: 'All Orders', delivered: 'Delivered', in_transit: 'In Transit', no_orders_found: 'No orders found',
    orders_tab: '📋 Orders', earnings_tab: '💰 Earnings', register_tab: '📝 Register',
    partner_title: '🚚 Partner Dashboard', this_month: 'This Month', deliveries: 'Deliveries', bonus: 'Bonus',
    weekly_earn: '📊 Weekly Earnings', recent_deliveries: '📋 Recent Deliveries',
    reg_title: '📝 Partner Registration', name_label: 'Full Name', zone_label: 'Zone',
    vehicle_lbl: 'Vehicle', vnum_label: 'Vehicle Number', register_btn: '✅ Register',
    online: 'Online', today: 'Today', rate_btn: 'Rate', track_order: 'Track',
    nav_home: 'Home', nav_book: 'Book', nav_track: 'Track', nav_partner: 'Partner',
    nav_history: 'History', nav_support: 'Support',
  },
  ta: {
    city: 'வேலூர்', login: 'உள்நுழை', hero_h1_acc: 'வேகம். புத்திசாலி.', hero_h1_sub: 'நம்பகமான டெலிவரி.',
    hero_sub: 'வேலூர் முழுவதும் டெலிவரி — விரைவாக, பாதுகாப்பாக & சரியான நேரத்தில்.',
    hero_live: 'வேலூர் மாவட்டத்தில் இப்போது நேரலை', lang_label: '🌐 மொழி தேர்வு:',
    hero_title: 'எங்கும் நிமிடங்களில் பொதிகளை அனுப்புங்கள் 🚀',
    hero_pickup: '📍 பிக்அப் இடம்', hero_drop: '🎯 டிராப் இடம்', hero_btn: 'மதிப்பீடு பெறு →',
    carousel_1_title: '30 நிமிடங்களில் விரைவான டெலிவரி', carousel_1_sub: 'நகரம் முழுவதும் மின்னல் வேகத்தில் உங்கள் பொதிகளை டெலிவரி செய்யுங்கள்.',
    carousel_2_title: 'கடைகளுக்கு மொத்த டெலிவரி', carousel_2_sub: 'கடை உரிமையாளர்களுக்கு சிறப்பு விலைகள் மற்றும் சொந்த வாகனங்கள்.',
    carousel_3_title: 'பாதுகாப்பான கூரியர்', carousel_3_sub: 'ஒவ்வொரு பொதியும் காப்பீடு செய்யப்பட்டு நேரலையில் கண்காணிக்கப்படுகிறது.',
    ticker_1: '🔥 முதல் டெலிவரிக்கு 20% தள்ளுபடி', ticker_2: '📦 இன்று இலவச பிக்அப்',
    route1: 'வேலூர் → சென்னை', route2: 'வேலூர் → பெங்களூரு', route3: 'வேலூர் → ராணிப்பேட்',
    route4: 'வேலூர் → காட்பாடி', route5: 'வேலூர் → குடியாத்தம்', min: 'நிமி', hr: 'மணி',
    home_q: 'என்ன செய்ய விரும்புகிறீர்கள்?', home_q_sub: 'தொடங்க ஒரு விருப்பத்தை தேர்ந்தெடுங்கள்',
    card_book: 'டெலிவரி பதிவு', card_book_desc: 'வேலூரில் எங்கும் பொதி அனுப்புங்கள் — விரைவாக.',
    card_track: 'ஆர்டர் கண்காணிப்பு', card_track_desc: 'உங்கள் டெலிவரி நிலையை நேரலையில் பாருங்கள்.',
    card_partner: 'பார்ட்னர் உள்நுழைவு', card_partner_desc: 'ஆர்டர்கள் ஏற்று வருவாயை கண்காணியுங்கள்.',
    card_support: 'ஆதரவு', card_support_desc: 'பிரச்சனை உள்ளதா? விரைவில் தீர்க்கிறோம்.',
    stat_orders: 'டெலிவரி செய்யப்பட்டவை', stat_partners: 'செயலில் உள்ள பார்ட்னர்கள்', stat_cities: 'நகரங்கள்',
    feat_title: 'ஏன் SmartDrop?', feat_sub: 'வேலூரின் தேவைகளுக்காக கட்டமைக்கப்பட்டது',
    f1t: 'எக்ஸ்பிரஸ் டெலிவரி', f1d: '10 கி.மீ க்கு கீழ் 20–30 நிமிடங்களில்.',
    f2t: 'பல கட்டண முறைகள்', f2d: 'UPI, கார்டு, நெட் பேங்கிங் அல்லது COD.',
    f3t: 'நேரலை கண்காணிப்பு', f3d: 'பிக்அப் முதல் வீட்டுவாசல் வரை புதுப்பிப்புகள்.',
    f4t: 'OTP பாதுகாப்பு', f4d: 'பிக்அப் & டெலிவரியில் இரட்டை OTP.',
    f5t: 'பார்ட்னர் வேலைவாய்ப்பு', f5d: '₹30/டெலிவரி + ₹5/கி.மீ + போனஸ்.',
    f6t: 'பாதுகாப்பான நிர்வாகம்', f6d: 'மறைக்கப்பட்ட போர்டல். பங்குதர அணுகல் மட்டுமே.',
    footer_tag: 'வேகம். புத்திசாலி. நம்பகமான டெலிவரி.', footer_rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    book_title: '📦 டெலிவரி பதிவு', book_sub: 'புத்திசாலி விலை · பல கட்டணங்கள் · உடனடி பார்ட்னர் நியமனம்',
    pickup_label: '📍 பிக்அப் இடம்', drop_label: '🎯 டிராப் இடம்',
    parcel_type: '📦 பொதி வகை', type_normal: 'சாதாரண', type_fragile: 'உடையக்கூடியது', type_food: 'உணவு', type_doc: 'ஆவணம்',
    size_label: '📐 பொதி அளவு', size_small: 'சிறியது (+₹10)', size_medium: 'நடுத்தரம் (+₹20)', size_large: 'பெரியது (+₹40)',
    speed_label: '⚡ வேகம்', speed_normal: '🚶 சாதாரண', speed_express: '⚡ எக்ஸ்பிரஸ்',
    pay_label: '💳 கட்டண முறை', customer_label: 'உங்கள் பெயர்', phone_label: 'தொலைபேசி எண்',
    place_order: '🚀 ஆர்டர் செய்', calculating: 'கட்டணம் கணக்கிடுகிறோம்...',
    fare_summary: '💰 கட்டண சுருக்கம்', base_fare: 'அடிப்படை கட்டணம்', distance: 'தூரம்',
    type_charge: 'வகை கட்டணம்', size_charge: 'அளவு கட்டணம்', express_charge: 'எக்ஸ்பிரஸ் கட்டணம்', total_fare: 'மொத்த கட்டணம்',
    delivery_type: '📦 டெலிவரி வகை', single: 'ஒற்றை', multi: 'பல', bulk: 'மொத்தம்',
    add_item: '➕ பொருள் சேர்', remove: 'அகற்று', item_name: 'பொருள் பெயர்', quantity: 'அளவு',
    total_weight: 'மொத்த எடை', weight_kg: 'கி.கி', per_kg_rate: 'கி.கி வீதம்', item_charge: 'பொருள் கட்டணம்', bulk_package: 'மொத்த பொதி',
    track_title: '📍 உங்கள் ஆர்டரை கண்காணிக்கவும்', track_sub: 'நேரலை நிலை காண உங்கள் ஆர்டர் ID உள்ளிடுங்கள்',
    track_placeholder: 'எ.கா. ORD-1001', track_btn: 'கண்காணி', not_found: 'ஆர்டர் கிடைக்கவில்லை.',
    support_title: '💬 வாடிக்கையாளர் ஆதரவு', support_sub: '24 மணி நேரத்தில் பதிலளிப்போம்',
    your_name: 'உங்கள் பெயர்', contact_label: 'தொலைபேசி / மின்னஞ்சல்', order_id_opt: 'ஆர்டர் ID (விருப்பமானது)',
    issue_type: 'பிரச்சனை வகை', delivery_issue: 'டெலிவரி பிரச்சனை', payment_issue: 'கட்டண பிரச்சனை',
    partner_issue: 'பார்ட்னர் பிரச்சனை', other_issue: 'மற்றவை', describe_issue: 'உங்கள் பிரச்சனையை விவரிக்கவும்',
    submit_btn: '📤 கோரிக்கை அனுப்பு', ticket_submitted: 'டிக்கெட் சமர்ப்பிக்கப்பட்டது!',
    ticket_id_label: 'உங்கள் டிக்கெட் ID:', ticket_respond: '24 மணி நேரத்தில் பதிலளிப்போம்.',
    submit_another: 'மற்றொன்று சமர்ப்பிக்கவும்',
    history_title: '📋 ஆர்டர் வரலாறு', history_sub: 'உங்கள் அனைத்து டெலிவரிகளும்',
    all_orders: 'அனைத்து ஆர்டர்களும்', delivered: 'டெலிவரி செய்யப்பட்டது', in_transit: 'போக்குவரத்தில்', no_orders_found: 'ஆர்டர்கள் இல்லை',
    orders_tab: '📋 ஆர்டர்கள்', earnings_tab: '💰 வருவாய்', register_tab: '📝 பதிவு',
    partner_title: '🚚 பார்ட்னர் டாஷ்போர்டு', this_month: 'இந்த மாதம்', deliveries: 'டெலிவரிகள்', bonus: 'போனஸ்',
    weekly_earn: '📊 வாராந்திர வருவாய்', recent_deliveries: '📋 சமீபத்திய டெலிவரிகள்',
    reg_title: '📝 பார்ட்னர் பதிவு', name_label: 'முழு பெயர்', zone_label: 'மண்டலம்',
    vehicle_lbl: 'வாகனம்', vnum_label: 'வாகன எண்', register_btn: '✅ பதிவு செய்',
    online: 'ஆன்லைன்', today: 'இன்று', rate_btn: 'மதிப்பீடு', track_order: 'கண்காணி',
    nav_home: 'முகப்பு', nav_book: 'பதிவு', nav_track: 'கண்காணி', nav_partner: 'பார்ட்னர்',
    nav_history: 'வரலாறு', nav_support: 'ஆதரவு',
  },
};

const LangContext = createContext(null);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || translations['en'][key] || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
